### ISSUE TITLE
failed to load pretrained model

### ISSUE THREAD

**Issue by burui11087** [ildoonet/tf-mobilenet-v2#10]
Hi 

Thanks for your share. I download pretrained model from official website, but I can't restore all weights because some layers shape not match. I want to know did you restore all weights successfully?

Thanks again!

**Comment by YYsmith** [comment]
I also find this problem, have you did it?

**Comment by burui11087** [comment]
@YYsmith  I'm using the official version. https://github.com/tensorflow/models/tree/master/research/slim/nets/mobilenet

**Comment by YYsmith** [comment]
thank you. I also used the official version later and did it.
