### ISSUE TITLE
About the pretrained model

### ISSUE THREAD

**Issue by hanjf12** [ildoonet/tf-mobilenet-v2#2]
hello ,is there any image-net pretrained model?

**Comment by ildoonet** [comment]
Currently, the training for models is being executed. It will take weeks.

**Comment by ildoonet** [comment]
I trained in a few ways, but I failed to replicate the result from the original paper.

but You can use the pretrained weight in tensorflow now : https://github.com/tensorflow/models/tree/master/research/slim#pre-trained-models
