### ISSUE TITLE
Why not tensorpack?

### ISSUE THREAD

**Issue by ppwwyyxx** [ildoonet/tf-mobilenet-v2#4]
Out of curiosity -- 

I noticed that a large part of the code here(the training helpers and the data loaders) is based on tensorpack. You're probably quite familiar with how tensorpack works. So I'm wondering is there any reason in particular that makes you write your own training code instead of just using tensorpack to train it? Just want to know how users think of tensorpack and what to improve to make it more usable to people.

**Comment by ildoonet** [comment]
@ppwwyyxx I'm very thankful for your work! I will plan to use tensorpack entirely. But, tensorpack's api document is somewhat hard for the beginners. Also, tensorflow's new estimator is a kind of rival for tensorpack.. 

But I really love tensorpack because it is super fast. Thanks.
